name: Deploy GH Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - chore/fix-typedoc

permissions:
  contents: write
  id-token: write # For publishing to npm using --provenance

jobs:
  generate-docs:
    name: Generate API docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        shell: bash
        run: npm ci --include=dev

      - name: Build package
        shell: bash
        run: npx turbo run build --filter="{./packages/*}"

      - name: Build docs
        shell: bash
        run: npm run docs

      - name: create a new document artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs
          retention-days: 1

  deploy-docs:
    needs: generate-docs
    name: Deploy API docs

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: checkout the gh-pages repo
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove old documentation
        run: rm -rf docs

      - name: Download the new documentation
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs

      - name: Extract and commit new docs
        run: |
          # Add and commit changes
          git add .

          # Only commit if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "CI updated the documentation - ${{ github.sha }}"
            git push
          else
            echo "No changes to commit"
          fi